project:
  type: website

website:
  title: "Leon's IS415 (GAA) Journey"
  navbar:
    left:
    - text: "Hands-On Exercise"
      menu:
        - text: "Hands-On Exercise 2"
          href: "Hands-On_Ex/Hands-On_Ex02/Hands-On_Ex02.html"
        - text: "Hands-On Exercise 3"
          href: "Hands-On_Ex/Hands-On_Ex03/Hands-On_Ex03.html"
        - text: "Hands-On Exercise 4 (1st Order)"
          href: "Hands-On_Ex/Hands-On_Ex04/Hands-On_Ex04.html"
        - text: "Hands-On Exercise 4 (2nd Order)"
          href: "Hands-On_Ex/Hands-On_Ex04/Hands-On_Ex04_2.html"
        - text: "Hands-On Exercise 6"
          href: "Hands-On_Ex/Hands-On_Ex06/Hands-On_Ex06.html"
        - text: "Hands-On Exercise 7 (Part 1)"
          href: "Hands-On_Ex/Hands-On_Ex07/Hands-On_Ex07.html"
        - text: "Hands-On Exercise 7 (Part 2)"
          href: "Hands-On_Ex/Hands-On_Ex07/Hands-On_Ex07_2.html"
    - text: "In-Class Exercise"
      menu:
        - text: "In-Class Exercise 2"
          href: "In-Class_Ex/In-Class_Ex02/In-Class_Ex02.html"
        - text: "In-Class Exercise 3"
          href: "In-Class_Ex/In-Class_Ex03/In-Class_Ex03.html"
        - text: "In-Class Exercise 4 (1st Order)"
          href: "In-Class_Ex/In-Class_Ex04/In-Class_Ex04.html"
        - text: "In-Class Exercise 4 (2nd Order)"
          href: "In-Class_Ex/In-Class_Ex04/In-Class_Ex04_2.html"
        - text: "In-Class Exercise 5"
          href: "In-Class_Ex/In-Class_Ex05/In-Class_Ex05.html"
        - text: "In-Class Exercise 6"
          href: "In-Class_Ex/In-Class_Ex06/In-Class_Ex06.html"
        - text: "In-Class Exercise 7"
          href: "In-Class_Ex/In-Class_Ex07/In-Class_Ex07.html"
    - text: "Take-Home Exercise"
      menu:
        - text: "Take-Home Exercise 1"
          href: "Take-Home_Ex/Take-Home_Ex01/Take-Home_Ex01.html"
        - text: "Take-Home Exercise 2"
          href: "Take-Home_Ex/Take-Home_Ex02/Take-Home_Ex02.html"
        - text: "Take-Home Exercise 3"
          href: "Take-Home_Ex/Take-Home_Ex03/Take-Home_Ex03.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      light: [flatly]
      dark: [darkly]
    css: styles.css
    toc: true

editor: visual

