---
title: "In-Class Exercise 2: Geospatial Data Wrangling"
date: "`r Sys.Date()`"
date-modified: "`r Sys.Date()`"
format: html
execute:
  message: false
  warning: false
editor: visual
---

## Install of sf & tidyverse

```{r}
#| code-fold: true
#| code-summary: "Show The Code"
pacman::p_load(sf, tidyverse, funModeling)
```

## Importing Geospatial

The geoBoundaries data set

```{r}
#| code-fold: true
#| code-summary: "Show The Code"
geoNGA <- st_read("data/geospatial/",
                  layer = "geoBoundaries-NGA-ADM2") %>%
  st_transform(crs = 26392)
```

The NGA data set

```{r}
#| code-fold: true
#| code-summary: "Show The Code"
NGA <- st_read("data/geospatial/",
                  layer = "nga_admbnda_adm2_osgof_20190417") %>%
  st_transform(crs = 26392)
```

## Importing Aspatial Data

```{r}
#| code-fold: true
#| code-summary: "Show The Code"
wp_nga <- read_csv("data/aspatial/WPdx.csv") %>%
  filter(`#clean_country_name` == "Nigeria")
```

## Converting Aspatial Data into Geospatial

```{r}
#| code-fold: true
#| code-summary: "Show The Code"
wp_nga$Geometry = st_as_sfc(wp_nga$`New Georeferenced Column`)
wp_nga
```

```{r}
#| code-fold: true
#| code-summary: "Show The Code"
wp_sf <- st_sf(wp_nga, crs=4326)
wp_sf
```

## Projection Transformation

```{r}
#| code-fold: true
#| code-summary: "Show The Code"
wp_sf <- wp_sf %>%
  st_transform(crs = 26392)
```

```{r}
st_crs(wp_sf)
```
