---
title: "In-Class Exercise 4: 1st Order Spatial Point Patterns Analysis Methods"
date: "30 January 2023"
date-modified: "`r Sys.Date()`"
format: html
execute:
  eval: true
  echo: true
  message: false
  warning: false
editor: visual
---

# Getting Started

## Importing Modules

```{r}
pacman::p_load(maptools, sf, raster, spatstat, tmap)
```

## Importing Data

```{r}
childcare_sf <- st_read("data/child-care-services-geojson.geojson") %>%
  st_transform(crs = 3414)
```

```{r}
sg_sf <- st_read(dsn = "data", layer="CostalOutline")
```

```{r}
mpsz_sf <- st_read(dsn = "data", 
                layer = "MP14_SUBZONE_WEB_PL")
```

## Mapping the Geospatial Data Sets

```{r}
tmap_mode('view')
tm_shape(childcare_sf)+
  tm_dots(alph=0.5, size=0.01)+
  tm_view(set.zoom.limits = c(11,14))
```

```{r}
tmap_mode('plot')
```

# Geospatial Data Wrangling

## Converting sf Data Frame to sp's Spatial Class

```{r}
childcare <- as_Spatial(childcare_sf)
mpsz <- as_Spatial(mpsz_sf)
sg <- as_Spatial(sg_sf)
```

```{r}
childcare
```

```{r}
mpsz
```

```{r}
sg
```

## Converting the Spatial Class into Generic sp Format

```{r}
childcare_sp <- as(childcare, "SpatialPoints")
sg_sp <- as(sg, "SpatialPolygons")
```

```{r}
childcare_sp
```

```{r}
sg_sp
```

## Converting the Generic sp Format into Spatstat's ppp Format

```{r}
childcare_ppp <- as(childcare_sp, "ppp")
childcare_ppp
```

```{r}
plot(childcare_ppp)
```

```{r}
summary(childcare_ppp)
```
